### ISSUE TITLE
docker.dev - dotnet watch projects intermittent failure with "same key has been added"

### ISSUE THREAD

**Issue by acnicholls** [acnicholls/NSW#104]
api-1    | Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: /app/api/src/NSW_Api/bin/Debug/net7.0/System.Windows.Extensions.dll
api-1    |    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
api-1    |    at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.<CheckForChangedFiles>b__23_0(FileSystemInfo f)
api-1    |    at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.ForeachEntityInDirectory(DirectoryInfo dirInfo, Action`1 fileAction)
api-1    |    at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.ForeachEntityInDirectory(DirectoryInfo dirInfo, Action`1 fileAction)
api-1    |    at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.ForeachEntityInDirectory(DirectoryInfo dirInfo, Action`1 fileAction)
api-1    |    at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.ForeachEntityInDirectory(DirectoryInfo dirInfo, Action`1 fileAction)
api-1    |    at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.CheckForChangedFiles()
api-1    |    at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.PollingLoop()

**Comment by acnicholls** [comment]
apparently the fix is easy

https://stackoverflow.com/questions/67048253/dotnet-watch-crashes-in-docker

**Comment by acnicholls** [comment]
fix seems to work a bit, initial load had two fails for only idp service and worked flawlessly after the build.
