### ISSUE TITLE
"Edit This Post" button on View Post page doesn't work

### ISSUE THREAD

**Issue by acnicholls** [acnicholls/NSW#12]
When viewing a post and clicking the 'Edit this Post' button the application navigates to 

http://localhost/NSW_trunk/Posts/EditPost.aspx?postID=311966

but the page's controls are empty.
 I checked the database log table and the error is as follows;
System.OverflowException: Value was either too large or too small for an Int16.
   at System.Int16.Parse(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt16(String value)
   at NSW.Posts.EditPost.Page_Load(Object sender, EventArgs e) in C:\Users\Anthony\Documents\Visual Studio 2015\Projects\Github\NSW\NSW\NSW_Portal\Posts\EditPost.aspx.cs:line 27
Value was either too large or too small for an Int16.
   at System.Int16.Parse(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt16(String value)
   at NSW.Posts.EditPost.Page_Load(Object sender, EventArgs e) in C:\Users\Anthony\Documents\Visual Studio 2015\Projects\Github\NSW\NSW\NSW_Portal\Posts\EditPost.aspx.cs:line 27

**Comment by acnicholls** [comment]
fixed in EditPost.aspx, Convert.ToInt16 was too small for the PostId.  Changed to ToInt32 which should allow up to 2B records before crashing again.
